// ============================================================
// STUDYVUI — Danh mục "Dạng bài" Toán Lớp 1, theo từng bài học (node/tuần).
// Nguồn: mockup "Xưởng duyệt dạng bài Toán — theo node trạm (Lớp 1)" đã CHỐT
// (35 node, 269 dạng bài gốc → 290 sau khi tách theo node — 1 số bài SGK dùng
// chung cho 2 node liền kề nên dạng bài lặp lại). Dùng trong form "Thêm câu hỏi"
// (question-dialog.tsx): chọn Bài học → lọc "Dạng bài" theo đúng node đó →
// auto-fill Skill (2 từ, gộp nhóm rộng) + gợi ý placeholder Đề bài/Đáp án.
// Ghi chú SGK chi tiết: PLAN/TOÁN/ghi_chu_dang_bai_sgk/ (repo STUDYVUI).
// ============================================================

export type MathArchetypeFeas = "formula" | "image" | "engine";

export interface MathArchetype {
  /** Tên dạng bài — hiện trong dropdown "Dạng bài". */
  label: string;
  /** Độ khả thi: formula = sinh tự động được; image = cần ảnh gắn tay;
   *  engine = cần builtin generator riêng (xem lib/math-gen/builtins.ts). */
  feas: MathArchetypeFeas;
  /** Skill 2 từ, đã gộp nhóm rộng (vd nhiều dạng đếm → "Đếm số"). */
  skill: string;
  /** Gợi ý đặt vào placeholder ô "Đề bài" — 1 ví dụ cụ thể, không phải giá trị mặc định. */
  promptHint: string;
  /** Gợi ý đặt vào placeholder 4 ô "Lựa chọn A-D" (thứ tự tương ứng). */
  optionHints: string[];
}

/** key = mã bài học (Lesson.code), vd "G1_W01_MATH". */
export const MATH_ARCHETYPES_G1: Record<string, MathArchetype[]> = {
  "G1_W01_MATH": [
    { label: "Đếm số lượng vật trong hình", feas: "image", skill: "Đếm số", promptHint: "Có mấy con mèo trong hình?", optionHints: ["3", "4", "2", "5"] },
    { label: "Điền số còn thiếu trong dãy 0-5", feas: "formula", skill: "Dãy số", promptHint: "Điền số còn thiếu: 0, 1, 2, ?, 4, 5", optionHints: ["5", "3", "2", "1"] },
    { label: "Đếm theo điều kiện nhãn/màu dán trên vật [MỚI]", feas: "image", skill: "Đếm số", promptHint: "Có mấy con gà con dán nhãn số 2 trên mình?", optionHints: ["1", "4", "3", "2"] },
    { label: "Chọn số đúng với số lượng (3 đáp án cho sẵn)", feas: "image", skill: "Đếm số", promptHint: "Có mấy con gà con trong hình? Chọn số đúng.", optionHints: ["3", "1", "4"] },
    { label: "Đếm nhiều loại vật trong 1 tranh phong cảnh lớn", feas: "image", skill: "Đếm số", promptHint: "Trong tranh phong cảnh, có mấy con chim đang bay?", optionHints: ["6", "3", "4", "5"] },
  ],
  "G1_W02_MATH": [
    { label: "Đếm số lượng vật (6-10)", feas: "image", skill: "Đếm số", promptHint: "Có mấy con ong trong hình?", optionHints: ["7", "9", "8", "6"] },
    { label: "Điền số còn thiếu dãy tăng/giảm 0-10", feas: "formula", skill: "Dãy số", promptHint: "Điền số còn thiếu: 1, ?, -1, -2, -3", optionHints: ["0", "4", "2", "1"] },
    { label: "Đếm số con vật thoả điều kiện đếm-chân/thuộc tính [MỚI]", feas: "image", skill: "Đếm số", promptHint: "Có mấy con vật có đúng 6 chân trong hình?", optionHints: ["2", "3", "4", "5"] },
    { label: "Chọn số đúng với số lượng (3 đáp án)", feas: "image", skill: "Đếm số", promptHint: "Có mấy con thỏ trong hình? Chọn số đúng.", optionHints: ["10", "8", "9"] },
    { label: "Đếm nhiều loại trong tranh phong cảnh lớn", feas: "image", skill: "Đếm số", promptHint: "Trong tranh, có mấy con vịt bơi dưới ao?", optionHints: ["7", "6", "8", "5"] },
  ],
  "G1_W03_MATH": [
    { label: "Chọn câu đúng khi so sánh 2 nhóm vật (nhiều hơn/ít hơn)", feas: "image", skill: "So sánh", promptHint: "Có 5 con bướm và 4 bông hoa. Câu nào đúng?", optionHints: ["Số hoa nhiều hơn số bướm", "Hai số bằng nhau", "Số bướm nhiều hơn số hoa"] },
    { label: "So sánh gián tiếp qua vật gắn liền (nấm đội trên lưng nhím) [MỚI]", feas: "image", skill: "So sánh", promptHint: "Có 4 con nhím, mỗi con đội 1 cây nấm trên lưng. Câu nào đúng?", optionHints: ["Số nhím bằng số nấm", "Số nhím nhiều hơn số nấm", "Số nấm nhiều hơn số nhím"] },
    { label: "Thêm vật để số lượng bằng/nhiều hơn nhóm kia", feas: "image", skill: "Đếm số", promptHint: "Có 3 quả cà rốt và 5 quả bắp cải. Cần thêm mấy quả cà rốt để bằng số bắp cải?", optionHints: ["3", "1", "4", "2"] },
    { label: "Điền dấu >, <, =", feas: "formula", skill: "So sánh", promptHint: "Điền dấu thích hợp: 9 ... 3", optionHints: [">", "<", "="] },
    { label: "Tìm số thoả bất đẳng thức (chọn 1 trong 2 số)", feas: "formula", skill: "Toán đố", promptHint: "Số nào điền vào ô trống để ? > 3 đúng?", optionHints: ["0", "8", "2", "4"] },
    { label: "Đếm 2 nhóm vật rồi điền dấu so sánh", feas: "image", skill: "Đếm số", promptHint: "Đếm số con kiến và số quả dưa hấu trong hình rồi so sánh.", optionHints: ["=", ">", "<"] },
    { label: "Tìm nhóm nhiều nhất/ít nhất trong 3 nhóm", feas: "image", skill: "So sánh", promptHint: "Tàu A chở 3 thùng, tàu B chở 4 thùng, tàu C chở 2 thùng. Tàu nào chở nhiều nhất?", optionHints: ["Tàu A", "Tàu B", "Tàu C"] },
  ],
  "G1_W04_MATH": [
    { label: "Điền dấu >, <, =", feas: "formula", skill: "So sánh", promptHint: "Điền dấu thích hợp: 1 ... 2", optionHints: [">", "<", "="] },
    { label: "Tìm số thoả bất đẳng thức (chọn 1 trong 2 số)", feas: "formula", skill: "Toán đố", promptHint: "Số nào điền vào ô trống để ? > 5 đúng?", optionHints: ["5", "7", "6", "10"] },
    { label: "Đếm 2 nhóm vật rồi điền dấu so sánh", feas: "image", skill: "Đếm số", promptHint: "Đếm số con kiến và số quả dưa hấu trong hình rồi so sánh.", optionHints: [">", "<", "="] },
    { label: "Tìm nhóm nhiều nhất/ít nhất trong 3 nhóm", feas: "image", skill: "So sánh", promptHint: "Tàu A chở 3 thùng, tàu B chở 4 thùng, tàu C chở 2 thùng. Tàu nào chở nhiều nhất?", optionHints: ["Tàu C", "Tàu A", "Tàu B"] },
  ],
  "G1_W05_MATH": [
    { label: "\"X gồm A và mấy?\" — tách số cơ bản", feas: "formula", skill: "Tách số", promptHint: "7 gồm 2 và mấy?", optionHints: ["0", "4", "5", "7"] },
    { label: "Đếm 2 nhóm rồi gộp tổng", feas: "image", skill: "Tách số", promptHint: "Bể cá trái có 3 con, bể cá phải có 2 con. Cả hai bể có mấy con cá?", optionHints: ["5", "4", "6", "7"] },
    { label: "Tách số minh hoạ bằng que tính", feas: "image", skill: "Tách số", promptHint: "Tách 6 que tính thành 2 nhóm, 1 nhóm có 2 que. Nhóm còn lại có mấy que?", optionHints: ["5", "4", "6", "3"] },
    { label: "Đếm theo 2 thuộc tính (màu/hình) rồi tách số", feas: "image", skill: "Tách số", promptHint: "Có 5 viên kẹo, trong đó 2 viên màu cam. Có mấy viên màu đỏ?", optionHints: ["2", "3", "4"] },
  ],
  "G1_W06_MATH": [
    { label: "Đếm tổng số lượng nhiều loại trong tranh", feas: "image", skill: "Đếm số", promptHint: "Trong bể cá nhiều màu, có tất cả mấy con cá?", optionHints: ["7", "6", "5", "8"] },
    { label: "Dãy số cách đều — điền số thiếu", feas: "formula", skill: "Dãy số", promptHint: "Điền số còn thiếu: 2, ?, 6, 8", optionHints: ["5", "4", "3", "9"] },
    { label: "Dot-to-dot: nối chấm theo thứ tự số [MỚI]", feas: "image", skill: "Tính toán", promptHint: "Nối các chấm theo thứ tự từ 1 đến 10. Chấm số 6 nằm ở vị trí nào trong dãy?", optionHints: ["Ở đầu", "Ở giữa", "Ở cuối"] },
    { label: "Tìm nhiều nhất/ít nhất trong 4 nhóm (A/B/C/D)", feas: "image", skill: "So sánh", promptHint: "4 cốc chè sen A, B, C, D có số hạt sen khác nhau. Cốc nào có NHIỀU hạt sen nhất?", optionHints: ["Cốc D", "Cốc A", "Cốc C", "Cốc B"] },
    { label: "So sánh — điền dấu", feas: "formula", skill: "So sánh", promptHint: "Điền dấu thích hợp: 5 ... 5", optionHints: [">", "<", "="] },
  ],
  "G1_W07_MATH": [
    { label: "Chọn hình đúng loại trong nhiều hình (vốn multi-select)", feas: "image", skill: "Nhận diện", promptHint: "Hình nào dưới đây là hình tam giác?", optionHints: ["Hình D", "Hình B", "Hình C", "Hình A"] },
    { label: "Đếm số hình theo loại trong 1 tranh ghép", feas: "image", skill: "Đếm số", promptHint: "Trong hình ngôi nhà ghép từ tam giác + chữ nhật + tròn, có mấy hình tam giác?", optionHints: ["1", "3", "4", "2"] },
    { label: "Chọn hình KHÔNG phải loại X", feas: "image", skill: "Nhận diện", promptHint: "Hình nào dưới đây KHÔNG PHẢI là hình vuông?", optionHints: ["Hình vuông đỏ", "Hình vuông xanh", "Hình tròn"] },
  ],
  "G1_W08_MATH": [
    { label: "Đếm số miếng bìa cấu thành 1 hình đã ghép sẵn", feas: "image", skill: "Đếm số", promptHint: "Hình mũi tên được ghép từ mấy miếng bìa hình tam giác?", optionHints: ["3", "5", "4", "2"] },
    { label: "Liên hệ đồ vật thật quanh mình với tên hình", feas: "image", skill: "Nhận diện", promptHint: "Bánh pizza thường có dạng hình gì?", optionHints: ["Hình tròn", "Hình chữ nhật", "Hình vuông", "Hình tam giác"] },
    { label: "Nhận diện quy luật lặp theo chu kỳ màu/hình [MỚI]", feas: "formula", skill: "Quy luật", promptHint: "Dãy hình lặp lại: tròn, tam giác, vuông, tròn, tam giác, vuông, tròn, ?, vuông. Hình còn thiếu là hình gì?", optionHints: ["Chữ nhật", "Vuông", "Tròn", "Tam giác"] },
    { label: "Đếm số mảnh tam giác cấu thành 1 hình ghép", feas: "image", skill: "Đếm số", promptHint: "Hình mũi tên (ghép từ nhiều tam giác nhỏ, có nét đứt chia ô) được ghép từ mấy miếng tam giác?", optionHints: ["5", "6", "3", "4"] },
  ],
  "G1_W09_MATH": [
    { label: "Viết phép cộng từ hình rồi tính", feas: "image", skill: "Nhận diện", promptHint: "Có 2 quả táo đỏ và 1 quả táo xanh. Viết phép cộng rồi tính tổng.", optionHints: ["4", "3", "5", "2"] },
    { label: "Hoàn thiện phép cộng có nhiều chỗ trống", feas: "image", skill: "Phép cộng", promptHint: "Có 4 con vịt dưới nước và 1 con trên bờ. Viết đầy đủ: 4 + 1 = ?", optionHints: ["3", "4", "6", "5"] },
    { label: "Tách-gộp liên hệ phép cộng (tháp số 2 tầng)", feas: "image", skill: "Tách số", promptHint: "Tháp số: tầng dưới có 2 và 3. Tầng trên (tổng) là mấy?", optionHints: ["5", "7", "4", "6"] },
    { label: "Tính nhẩm (danh sách phép cộng thuần)", feas: "formula", skill: "Phép cộng", promptHint: "Tính: 5 + 1 = ?", optionHints: ["6", "7", "3", "1"] },
    { label: "Tìm số hạng còn thiếu", feas: "formula", skill: "Tính toán", promptHint: "Số? 3 + ? = 10", optionHints: ["7", "5", "4", "6"] },
    { label: "Kỹ thuật đếm thêm (counting on)", feas: "image", skill: "Đếm số", promptHint: "Có 6 con cá, thêm 1 con nữa. Đếm thêm: 6, rồi mấy?", optionHints: ["6", "8", "7", "5"] },
    { label: "Bảng cộng — tổng cố định (vd luôn ra 7, ra 10)", feas: "formula", skill: "Phép cộng", promptHint: "Tính: 6 + ? = 7", optionHints: ["1", "3", "2", "4"] },
    { label: "Phép cộng 3 số hạng liên tiếp [MỚI]", feas: "formula", skill: "Phép cộng", promptHint: "Tính: 5 + 4 + 0 = ?", optionHints: ["5", "14", "6", "9"] },
    { label: "Tìm bóng bay ghi phép tính có kết quả cho trước (lọc)", feas: "image", skill: "Tính toán", promptHint: "Quả bóng nào ghi phép tính có kết quả bằng 10?", optionHints: ["5 + 3", "1 + 6", "8 + 2"] },
    { label: "Tháp số cộng dồn nhiều tầng [MỚI]", feas: "image", skill: "Phép cộng", promptHint: "Tháp số: đáy có 4,1,1,0. Ô đầu tầng 2 là 4+1=5. Ô thứ hai tầng 2 là mấy?", optionHints: ["3", "4", "2", "1"] },
    { label: "Minh hoạ tính chất giao hoán (a+b và b+a)", feas: "image", skill: "Tính toán", promptHint: "Biết 6 + 2 = 8. Vậy 2 + 6 = ?", optionHints: ["9", "8", "7", "6"] },
  ],
  "G1_W10_MATH": [
    { label: "Viết phép cộng từ hình rồi tính", feas: "image", skill: "Nhận diện", promptHint: "Có 2 quả táo đỏ và 1 quả táo xanh. Viết phép cộng rồi tính tổng.", optionHints: ["3", "5", "2", "4"] },
    { label: "Hoàn thiện phép cộng có nhiều chỗ trống", feas: "image", skill: "Phép cộng", promptHint: "Có 4 con vịt dưới nước và 1 con trên bờ. Viết đầy đủ: 4 + 1 = ?", optionHints: ["6", "4", "5", "3"] },
    { label: "Tách-gộp liên hệ phép cộng (tháp số 2 tầng)", feas: "image", skill: "Tách số", promptHint: "Tháp số: tầng dưới có 2 và 3. Tầng trên (tổng) là mấy?", optionHints: ["7", "4", "6", "5"] },
    { label: "Tính nhẩm (danh sách phép cộng thuần)", feas: "formula", skill: "Phép cộng", promptHint: "Tính: 5 + 0 = ?", optionHints: ["8", "4", "3", "5"] },
    { label: "Tìm số hạng còn thiếu", feas: "formula", skill: "Tính toán", promptHint: "Số? 2 + ? = 6", optionHints: ["7", "4", "1", "2"] },
    { label: "Kỹ thuật đếm thêm (counting on)", feas: "image", skill: "Đếm số", promptHint: "Có 6 con cá, thêm 1 con nữa. Đếm thêm: 6, rồi mấy?", optionHints: ["5", "7", "6", "8"] },
    { label: "Bảng cộng — tổng cố định (vd luôn ra 7, ra 10)", feas: "formula", skill: "Phép cộng", promptHint: "Tính: 6 + ? = 10", optionHints: ["3", "8", "1", "4"] },
    { label: "Phép cộng 3 số hạng liên tiếp [MỚI]", feas: "formula", skill: "Phép cộng", promptHint: "Tính: 5 + 3 + 1 = ?", optionHints: ["9", "8", "6", "12"] },
    { label: "Tìm bóng bay ghi phép tính có kết quả cho trước (lọc)", feas: "image", skill: "Tính toán", promptHint: "Quả bóng nào ghi phép tính có kết quả bằng 10?", optionHints: ["1 + 6", "8 + 2", "5 + 3"] },
    { label: "Tháp số cộng dồn nhiều tầng [MỚI]", feas: "image", skill: "Phép cộng", promptHint: "Tháp số: đáy có 4,1,1,0. Ô đầu tầng 2 là 4+1=5. Ô thứ hai tầng 2 là mấy?", optionHints: ["2", "4", "1", "3"] },
    { label: "Minh hoạ tính chất giao hoán (a+b và b+a)", feas: "image", skill: "Tính toán", promptHint: "Biết 6 + 2 = 8. Vậy 2 + 6 = ?", optionHints: ["9", "6", "8", "7"] },
  ],
  "G1_W11_MATH": [
    { label: "Viết phép trừ từ hình rồi tính", feas: "image", skill: "Nhận diện", promptHint: "Cây có 8 quả bưởi, 3 quả đang rụng. Viết phép trừ rồi tính số quả còn lại.", optionHints: ["6", "4", "5", "7"] },
    { label: "Bài toán lời văn 1 bước (tách số)", feas: "image", skill: "Tách số", promptHint: "Có 6 gấu bông và sóc bông, trong đó có 2 gấu bông. Hỏi có mấy sóc bông?", optionHints: ["2", "5", "4", "3"] },
    { label: "Bảng trừ — hiệu cố định", feas: "formula", skill: "Phép trừ", promptHint: "Tính: 7 − 4 = ?", optionHints: ["3", "8", "5", "1"] },
    { label: "Lọc phép tính theo kết quả cho trước", feas: "image", skill: "Tính toán", promptHint: "Bông hoa nào ghi phép tính có kết quả bằng 4?", optionHints: ["7 − 3", "6 − 1", "8 − 3"] },
    { label: "Số 0 trong phép trừ", feas: "formula", skill: "Phép trừ", promptHint: "Tính: 3 − 0 = ?", optionHints: ["2", "3", "5", "1"] },
    { label: "Ghép cặp phép tính cùng kết quả", feas: "image", skill: "Tính toán", promptHint: "Phép tính nào có cùng kết quả với 7 − 4?", optionHints: ["8 − 3", "5 − 2", "9 − 2"] },
    { label: "Phối hợp cộng-trừ trong 1 biểu thức (vd 3+6-4) [MỚI]", feas: "formula", skill: "Phép cộng", promptHint: "Tính: 2 + 5 − 1 = ?", optionHints: ["3", "10", "11", "6"] },
    { label: "Phép trừ 3 số hạng liên tiếp", feas: "formula", skill: "Phép trừ", promptHint: "Tính: 10 − 3 − 2 = ?", optionHints: ["9", "5", "4", "2"] },
  ],
  "G1_W12_MATH": [
    { label: "Viết phép trừ từ hình rồi tính", feas: "image", skill: "Nhận diện", promptHint: "Cây có 8 quả bưởi, 3 quả đang rụng. Viết phép trừ rồi tính số quả còn lại.", optionHints: ["4", "6", "5", "7"] },
    { label: "Bài toán lời văn 1 bước (tách số)", feas: "image", skill: "Tách số", promptHint: "Có 6 gấu bông và sóc bông, trong đó có 2 gấu bông. Hỏi có mấy sóc bông?", optionHints: ["4", "5", "2", "3"] },
    { label: "Bảng trừ — hiệu cố định", feas: "formula", skill: "Phép trừ", promptHint: "Tính: 6 − 4 = ?", optionHints: ["1", "5", "2", "4"] },
    { label: "Lọc phép tính theo kết quả cho trước", feas: "image", skill: "Tính toán", promptHint: "Bông hoa nào ghi phép tính có kết quả bằng 4?", optionHints: ["8 − 3", "7 − 3", "6 − 1"] },
    { label: "Số 0 trong phép trừ", feas: "formula", skill: "Phép trừ", promptHint: "Tính: 1 − 0 = ?", optionHints: ["1", "6", "2", "5"] },
    { label: "Ghép cặp phép tính cùng kết quả", feas: "image", skill: "Tính toán", promptHint: "Phép tính nào có cùng kết quả với 7 − 4?", optionHints: ["9 − 2", "8 − 3", "5 − 2"] },
    { label: "Phối hợp cộng-trừ trong 1 biểu thức (vd 3+6-4) [MỚI]", feas: "formula", skill: "Phép cộng", promptHint: "Tính: 4 + 4 − 3 = ?", optionHints: ["4", "7", "10", "5"] },
    { label: "Phép trừ 3 số hạng liên tiếp", feas: "formula", skill: "Phép trừ", promptHint: "Tính: 7 − 3 − 1 = ?", optionHints: ["0", "1", "6", "3"] },
  ],
  "G1_W13_MATH": [
    { label: "Hoàn thành bảng cộng đầy đủ (dạng lưới tam giác)", feas: "formula", skill: "Phép cộng", promptHint: "Tính: 4 + ? = 10", optionHints: ["4", "6", "5", "2"] },
    { label: "Hoàn thành bảng trừ đầy đủ (dạng lưới tam giác)", feas: "formula", skill: "Phép trừ", promptHint: "Tính: 3 − 2 = ?", optionHints: ["6", "5", "1", "3"] },
    { label: "Nối phép tính (ong) với kết quả (cánh hoa)", feas: "image", skill: "Tính toán", promptHint: "Con ong ghi phép tính 4+1 sẽ đậu vào cánh hoa số mấy?", optionHints: ["9", "6", "10", "5"] },
    { label: "Dây chuyền phép tính nhiều bước liên tiếp [MỚI]", feas: "formula", skill: "Tính toán", promptHint: "Số? 2 →(+2)→ ? →(−3)→ ?", optionHints: ["0", "6", "4", "1"] },
  ],
  "G1_W14_MATH": [
    { label: "Họ phép tính liên hệ cộng-trừ từ 1 hình (fact family) [MỚI]", feas: "formula", skill: "Nhận diện", promptHint: "Biết 7 + 1 = 8. Vậy 8 − 7 = ?", optionHints: ["1", "5", "4", "2"] },
    { label: "Bảng cộng dạng \"ngôi nhà\" — tổng đỉnh cố định", feas: "formula", skill: "Phép cộng", promptHint: "Ngôi nhà có tổng đỉnh là 9. Một hàng ghi 1 và ?. Số còn lại là mấy?", optionHints: ["13", "4", "8", "7"] },
    { label: "Tháp số cộng dồn", feas: "image", skill: "Phép cộng", promptHint: "Tháp số: tầng dưới có 1,2,1,0. Ô đầu tầng 2 là 1+2=3. Ô thứ hai tầng 2 là mấy?", optionHints: ["3", "2", "0", "1"] },
    { label: "Đếm + tính kết hợp (đếm số quả có kết quả bằng X)", feas: "image", skill: "Đếm số", promptHint: "Cây bưởi có nhiều quả ghi phép tính khác nhau. Có mấy quả ghi phép tính có kết quả bằng 5?", optionHints: ["3", "4", "5", "2"] },
    { label: "So sánh 1 số với giá trị 1 biểu thức [MỚI]", feas: "formula", skill: "So sánh", promptHint: "Điền dấu thích hợp: 2 + 2 ... 1", optionHints: [">", "<", "="] },
    { label: "Hoàn thiện phép cộng đầy đủ từ hình", feas: "image", skill: "Nhận diện", promptHint: "Có 4 bông hoa đỏ và 5 bông hoa xanh. Viết đầy đủ: 4 + 5 = ?", optionHints: ["8", "9", "7", "10"] },
  ],
  "G1_W15_MATH": [
    { label: "Chọn khối đúng loại (multi-select gốc)", feas: "image", skill: "Nhận diện", promptHint: "Hình nào dưới đây là khối lập phương?", optionHints: ["Khối D", "Khối B", "Khối A", "Khối C"] },
    { label: "Nối đồ vật thật với tên khối", feas: "image", skill: "Nhận diện", promptHint: "Khối rubik có dạng hình gì?", optionHints: ["Khối lập phương", "Khối cầu", "Khối hộp chữ nhật", "Khối trụ"] },
    { label: "Đếm khối theo loại + màu trong 1 công trình ghép", feas: "image", skill: "Đếm số", promptHint: "Trong ngôi nhà xếp từ nhiều khối màu, có mấy khối hộp chữ nhật màu đỏ?", optionHints: ["1", "4", "3", "2"] },
    { label: "Đếm khối lập phương trong hình chữ cái (T,H,C)", feas: "image", skill: "Đếm số", promptHint: "Chữ H được xếp bởi mấy khối lập phương nhỏ?", optionHints: ["8", "5", "6", "7"] },
    { label: "Nhận diện khối lập phương \"thật\" giữa các khối hộp gần giống", feas: "image", skill: "Nhận diện", promptHint: "Trong 3 khối hộp chữ nhật A, B, C, khối nào là khối lập phương thật (đều 3 chiều)?", optionHints: ["Khối C", "Khối B", "Khối A"] },
    { label: "Quy luật lặp khối 3D theo kích thước/màu", feas: "image", skill: "Đo lường", promptHint: "Dãy khối lặp lại: to, nhỏ, to, nhỏ, to, ?. Khối tiếp theo là khối gì?", optionHints: ["Nhỏ", "Vừa", "To"] },
    { label: "Xác định vị trí trước/sau/ở giữa (toa tàu)", feas: "image", skill: "Định vị", promptHint: "Đoàn tàu 4 toa đánh số 1-4. Toa nào ở giữa toa 1 và toa 3?", optionHints: ["Toa 1", "Toa 4", "Toa 2", "Toa 3"] },
    { label: "Xác định vị trí trên/dưới/giữa (đèn 3 tầng)", feas: "image", skill: "Định vị", promptHint: "Đèn giao thông 3 tầng: trên-giữa-dưới. Đèn ở giữa màu gì?", optionHints: ["Đỏ", "Xanh", "Vàng"] },
    { label: "Đếm số lượng theo hàng trước/sau", feas: "image", skill: "Định vị", promptHint: "Có 2 hàng bạn xem phim: hàng trước 5 bạn, hàng sau 4 bạn. Có tất cả mấy bạn?", optionHints: ["10", "9", "7", "8"] },
    { label: "Xác định thứ tự trái/phải của 1 hình trong dãy", feas: "formula", skill: "Định vị", promptHint: "Có 3 hình xếp từ trái sang phải: hình tròn, hình vuông, hình tam giác. Hình nào ở giữa?", optionHints: ["Hình tròn", "Hình tam giác", "Không có hình nào", "Hình vuông"] },
    { label: "Xác định màu mặt khối lập phương theo hướng nhìn 3D (trước/trên/phải) [MỚI]", feas: "image", skill: "Định vị", promptHint: "Khối lập phương A: mặt trước đỏ, mặt trên xanh, mặt phải vàng. Mặt trước của khối A màu gì?", optionHints: ["Xanh", "Vàng", "Đỏ"] },
  ],
  "G1_W16_MATH": [
    { label: "Xác định vị trí trước/sau/ở giữa (toa tàu)", feas: "image", skill: "Định vị", promptHint: "Đoàn tàu 4 toa đánh số 1-4. Toa nào ở giữa toa 1 và toa 3?", optionHints: ["Toa 2", "Toa 1", "Toa 4", "Toa 3"] },
    { label: "Xác định vị trí trên/dưới/giữa (đèn 3 tầng)", feas: "image", skill: "Định vị", promptHint: "Đèn giao thông 3 tầng: trên-giữa-dưới. Đèn ở giữa màu gì?", optionHints: ["Vàng", "Xanh", "Đỏ"] },
    { label: "Đếm số lượng theo hàng trước/sau", feas: "image", skill: "Định vị", promptHint: "Có 2 hàng bạn xem phim: hàng trước 5 bạn, hàng sau 4 bạn. Có tất cả mấy bạn?", optionHints: ["8", "10", "7", "9"] },
    { label: "Xác định thứ tự trái/phải của 1 hình trong dãy", feas: "formula", skill: "Định vị", promptHint: "Có 3 hình xếp từ trái sang phải: hình tròn, hình vuông, hình tam giác. Hình nào ở giữa?", optionHints: ["Không có hình nào", "Hình tròn", "Hình vuông", "Hình tam giác"] },
    { label: "Xác định màu mặt khối lập phương theo hướng nhìn 3D (trước/trên/phải) [MỚI]", feas: "image", skill: "Định vị", promptHint: "Khối lập phương A: mặt trước đỏ, mặt trên xanh, mặt phải vàng. Mặt trước của khối A màu gì?", optionHints: ["Xanh", "Vàng", "Đỏ"] },
    { label: "Chọn khối đúng loại (đa dạng khối)", feas: "image", skill: "Nhận diện", promptHint: "Trong 6 khối A-F, khối nào LÀ khối hộp chữ nhật?", optionHints: ["Khối C", "Khối D", "Khối A", "Khối F"] },
    { label: "Đọc số chấm mặt xúc xắc theo hướng nhìn (trước/phải/trên)", feas: "image", skill: "Định vị", promptHint: "Mặt trước của xúc xắc trong hình có mấy chấm?", optionHints: ["5", "3", "2", "4"] },
    { label: "So sánh số khối lập phương nhỏ giữa 2 hình ghép", feas: "image", skill: "Nhận diện", promptHint: "Hình bậc thang bên trái và hình chữ nhật bên phải, hình nào có nhiều khối lập phương nhỏ hơn?", optionHints: ["Bên phải nhiều hơn", "Bằng nhau", "Bên trái nhiều hơn"] },
  ],
  "G1_W17_MATH": [
    { label: "Nối số lượng (bể cá) với từ chỉ số", feas: "image", skill: "Đếm số", promptHint: "Bể cá có 6 con cá. Từ nào chỉ đúng số 6?", optionHints: ["Sáu", "Ba", "Tám"] },
    { label: "Đếm + so sánh nhiều loại vật trong tranh nông trại", feas: "image", skill: "Đếm số", promptHint: "Trong 3 con: thỏ (5 con), chó (3 con), trâu (2 con) — con vật nào ÍT nhất?", optionHints: ["Chó", "Trâu", "Thỏ"] },
    { label: "So sánh số với số/biểu thức", feas: "formula", skill: "So sánh", promptHint: "Điền dấu thích hợp: 1+2 ... 9", optionHints: [">", "<", "="] },
    { label: "Dot-to-dot dãy số 1-10", feas: "image", skill: "Dãy số", promptHint: "Nối các chấm từ 1 đến 10 theo hình ngôi sao. Số 7 nằm ở đâu trong dãy?", optionHints: ["Ở đầu dãy", "Chính giữa dãy", "Gần cuối dãy"] },
    { label: "Sắp xếp + lọc theo điều kiện kép (vừa lớn hơn A vừa bé hơn B)", feas: "formula", skill: "So sánh", promptHint: "Số nào vừa lớn hơn 2 vừa bé hơn 7?", optionHints: ["11", "6", "7", "8"] },
    { label: "Suy luận thứ tự khi có thêm 1 phần tử chen vào [MỚI]", feas: "image", skill: "Suy luận", promptHint: "Rùa xanh đi thứ nhất, rùa vàng thứ hai, rùa nâu thứ ba. Nếu rùa đỏ chen vào giữa xanh và vàng, rùa nâu đi thứ mấy?", optionHints: ["Thứ tư", "Thứ ba", "Thứ hai"] },
    { label: "Suy luận tách số có ràng buộc so sánh (đếm+so sánh+tách)", feas: "image", skill: "Tách số", promptHint: "3 bạn thỏ chạy vào 2 chuồng A và B, biết chuồng A nhiều hơn chuồng B. Mỗi chuồng có mấy bạn?", optionHints: ["A có 3, B có 0", "A có 2, B có 1", "A có 1, B có 2"] },
    { label: "Tính nhẩm tổng hợp cộng + trừ", feas: "formula", skill: "Phép cộng", promptHint: "Tính: 0 − 0 = ?", optionHints: ["3", "4", "1", "0"] },
    { label: "Dây chuyền phép tính nhiều bước", feas: "formula", skill: "Tính toán", promptHint: "Số? 6 →(+4)→ ? →(−5)→ ?", optionHints: ["5", "3", "7", "2"] },
    { label: "So sánh biểu thức với biểu thức", feas: "formula", skill: "So sánh", promptHint: "Điền dấu thích hợp: 1+5 ... 0+0", optionHints: [">", "<", "="] },
    { label: "Lọc phép tính theo kết quả cho trước", feas: "image", skill: "Tính toán", promptHint: "Bông hoa nào ghi phép tính có kết quả bằng 5?", optionHints: ["8 − 2", "7 − 4", "2 + 3"] },
    { label: "Lập phép tính đúng từ 1 tập số cho trước [MỚI]", feas: "formula", skill: "Tính toán", promptHint: "Từ các số 7, 2, 9, dấu + và =, phép tính nào ĐÚNG?", optionHints: ["2 + 9 = 7", "7 + 2 = 9", "7 + 9 = 2"] },
    { label: "Hoàn thiện phép cộng/trừ nhiều chỗ trống", feas: "image", skill: "Phép cộng", promptHint: "Đèn lồng: có 3 cái, thêm 1 cái. Viết đầy đủ: 3 + 1 = ?", optionHints: ["5", "4", "3"] },
  ],
  "G1_W18_MATH": [
    { label: "Chọn hình đúng loại (9 hình đa dạng)", feas: "image", skill: "Nhận diện", promptHint: "Trong 9 hình A-K, hình nào LÀ hình vuông?", optionHints: ["Hình A", "Hình B", "Hình F", "Hình I"] },
    { label: "Chọn khối đúng loại (6 khối)", feas: "image", skill: "Nhận diện", promptHint: "Trong 6 khối A-G, khối nào LÀ khối lập phương?", optionHints: ["Khối G", "Khối A", "Khối D"] },
    { label: "Quy luật lặp hình theo chu kỳ 3", feas: "formula", skill: "Quy luật", promptHint: "Dãy hình lặp lại chu kỳ 3: tròn, tam giác, vuông, tròn, tam giác, vuông, tròn, ?, vuông. Hình còn thiếu là hình gì?", optionHints: ["Vuông", "Chữ nhật", "Tam giác", "Tròn"] },
    { label: "Đếm tổng số lượng trong 4 tranh khác nhau", feas: "image", skill: "Đếm số", promptHint: "Tranh có 3 loại hoa khác nhau: 2, 3, 4 bông. Có tất cả mấy bông hoa?", optionHints: ["8", "7", "10", "9"] },
    { label: "Sắp xếp thứ tự dãy số cho trước", feas: "formula", skill: "Dãy số", promptHint: "Số nào bé nhất trong các số: 3, 9, 5?", optionHints: ["0", "2", "4", "3"] },
    { label: "Tính nhẩm bảng phép tính (6 phép độc lập)", feas: "formula", skill: "Tính toán", promptHint: "Tính: 6 + 3 = ?", optionHints: ["7", "9", "11", "10"] },
    { label: "Hoàn thiện phép tính nhiều chỗ trống", feas: "image", skill: "Tính toán", promptHint: "Đàn chim 10 con chia cành trên/dưới: cành trên 6 con. Viết đầy đủ: 6 + ? = 10", optionHints: ["3", "4", "5"] },
    { label: "Quy luật lặp hình chu kỳ 4", feas: "image", skill: "Quy luật", promptHint: "Dãy hình lặp chu kỳ 4: tròn, vuông, tam giác, thoi, tròn, vuông, tam giác, ?. Hình còn thiếu là hình gì?", optionHints: ["Vuông", "Tròn", "Tam giác", "Thoi"] },
  ],
  "G1_W19_MATH": [
    { label: "Đếm chục + đơn vị hoàn thiện số", feas: "image", skill: "Tách số", promptHint: "Có 2 chục và 3 đơn vị quả cà chua. Đó là số mấy?", optionHints: ["22", "13", "32", "23"] },
    { label: "\"X gồm A chục và B đơn vị\"", feas: "engine", skill: "Tách số", promptHint: "Số 23 gồm mấy chục và mấy đơn vị?", optionHints: ["3 chục 2 đơn vị", "2 chục 2 đơn vị", "2 chục 3 đơn vị", "3 chục 3 đơn vị"] },
    { label: "Dãy số liên tiếp — điền ô thiếu", feas: "formula", skill: "Dãy số", promptHint: "Điền số còn thiếu: 40, 41, 42, ?", optionHints: ["42", "43", "44", "47"] },
    { label: "Bảng số 1-100 — điền số thiếu", feas: "image", skill: "Dãy số", promptHint: "Trong bảng số 1-100, ô ngay sau số 32 (cùng hàng) là số mấy?", optionHints: ["33", "42", "31"] },
    { label: "Tìm số theo điều kiện (số có 1 chữ số / số tròn chục)", feas: "image", skill: "Tính toán", promptHint: "Trong các số 50, 30, 55, 44, 8 — số nào là số CÓ MỘT CHỮ SỐ?", optionHints: ["8", "50", "44"] },
  ],
  "G1_W20_MATH": [
    { label: "Đếm chục + đơn vị hoàn thiện số", feas: "image", skill: "Tách số", promptHint: "Có 2 chục và 3 đơn vị quả cà chua. Đó là số mấy?", optionHints: ["32", "13", "23", "22"] },
    { label: "\"X gồm A chục và B đơn vị\"", feas: "engine", skill: "Tách số", promptHint: "Số 23 gồm mấy chục và mấy đơn vị?", optionHints: ["3 chục 2 đơn vị", "3 chục 3 đơn vị", "2 chục 2 đơn vị", "2 chục 3 đơn vị"] },
    { label: "Dãy số liên tiếp — điền ô thiếu", feas: "formula", skill: "Dãy số", promptHint: "Điền số còn thiếu: 90, ?, 92, 93", optionHints: ["91", "94", "86", "95"] },
    { label: "Bảng số 1-100 — điền số thiếu", feas: "image", skill: "Dãy số", promptHint: "Trong bảng số 1-100, ô ngay sau số 32 (cùng hàng) là số mấy?", optionHints: ["42", "31", "33"] },
    { label: "Tìm số theo điều kiện (số có 1 chữ số / số tròn chục)", feas: "image", skill: "Tính toán", promptHint: "Trong các số 50, 30, 55, 44, 8 — số nào là số CÓ MỘT CHỮ SỐ?", optionHints: ["44", "8", "50"] },
  ],
  "G1_W21_MATH": [
    { label: "Đếm rồi so sánh 2 nhóm vật", feas: "image", skill: "Đếm số", promptHint: "Túi trái có 13 quả, túi phải có 16 quả. Túi nào có SỐ LỚN HƠN?", optionHints: ["Túi phải", "Bằng nhau", "Túi trái"] },
    { label: "Tìm số lớn hơn/bé hơn trong cặp", feas: "formula", skill: "So sánh", promptHint: "Số nào lớn hơn trong cặp: 12 và 54?", optionHints: ["54", "58", "57", "52"] },
    { label: "So sánh trực tiếp — điền dấu", feas: "formula", skill: "So sánh", promptHint: "Điền dấu thích hợp: 37 ... 15", optionHints: [">", "<", "="] },
    { label: "Tìm lớn nhất/bé nhất trong nhóm 3", feas: "formula", skill: "So sánh", promptHint: "Số nào lớn nhất trong 3 số: 36, 96, 23?", optionHints: ["101", "96", "98", "100"] },
    { label: "Đúng/Sai — nhận định phép so sánh cho sẵn", feas: "image", skill: "So sánh", promptHint: "Nhận định \"90 < 95\" là đúng hay sai?", optionHints: ["Sai", "Đúng"] },
    { label: "Mê cung điền dấu (bỏ yếu tố mê cung, giữ list so sánh)", feas: "formula", skill: "So sánh", promptHint: "Điền dấu thích hợp: 76 ... 45", optionHints: [">", "<", "="] },
    { label: "Toán lời văn so sánh 3 số cho sẵn", feas: "formula", skill: "So sánh", promptHint: "Lớp 1A có 38 học sinh, lớp 1B có 35 học sinh, lớp 1C có 40 học sinh. Lớp nào có NHIỀU học sinh nhất?", optionHints: ["Lớp 1A", "Lớp 1B", "Lớp 1C"] },
    { label: "Điền số thiếu trong bảng 100", feas: "image", skill: "Tính toán", promptHint: "Trong bảng số 1-100, ô liền dưới số 32 (cách 10) là số mấy?", optionHints: ["42", "22", "33"] },
    { label: "Liệt kê theo điều kiện (2 chữ số giống nhau, tròn chục)", feas: "image", skill: "Tính toán", promptHint: "Số nào sau đây có hai chữ số GIỐNG NHAU?", optionHints: ["55", "56", "54"] },
    { label: "Dãy số cách đều (bước 1 hoặc 2)", feas: "formula", skill: "Dãy số", promptHint: "Điền số còn thiếu: 19, 20, 21, ?", optionHints: ["22", "24", "23", "18"] },
    { label: "Chọn mảnh ghép đúng của bảng số 100 [MỚI]", feas: "image", skill: "Dãy số", promptHint: "Mảnh rèm che mất số 33 trong bảng số 100. Mảnh nào đúng?", optionHints: ["Mảnh B", "Mảnh C", "Mảnh A"] },
    { label: "\"X gồm mấy chục mấy đơn vị\"", feas: "engine", skill: "Tách số", promptHint: "Số 47 gồm mấy chục và mấy đơn vị?", optionHints: ["4 chục 7 đơn vị", "7 chục 4 đơn vị", "4 chục 4 đơn vị"] },
    { label: "Đếm ô vuông trong hình chữ cái — tìm nhiều/ít nhất", feas: "image", skill: "Đếm số", promptHint: "Hình chữ T và chữ L ghép từ ô vuông. Hình nào có 19 ô vuông?", optionHints: ["Hình L", "Hình T"] },
    { label: "Dãy số nhiều bước nhảy khác nhau", feas: "formula", skill: "Dãy số", promptHint: "Điền số còn thiếu: 5, 7, 9, ?", optionHints: ["9", "13", "10", "11"] },
    { label: "Tìm lớn hơn/bé hơn trong cặp số", feas: "formula", skill: "So sánh", promptHint: "Số nào bé hơn trong cặp: 72 và 19?", optionHints: ["22", "19", "23", "18"] },
    { label: "Tìm lớn nhất/bé nhất trong 3 số cho trước", feas: "formula", skill: "So sánh", promptHint: "Số nào lớn nhất trong 3 số: 10, 23, 71?", optionHints: ["71", "69", "76", "73"] },
    { label: "Chọn mảnh ghép đúng bảng số (biến thể rèm cửa)", feas: "image", skill: "Dãy số", promptHint: "Chú mèo làm rách 1 mảnh rèm che số 18 trong bảng số 1-49. Mảnh nào đúng?", optionHints: ["Mảnh C", "Mảnh A", "Mảnh B"] },
    { label: "Lập số có 2 chữ số từ tập thẻ số cho trước [MỚI]", feas: "formula", skill: "Tách số", promptHint: "Từ 2 trong 3 thẻ số 8, 3, 7, số nào sau đây LẬP ĐƯỢC?", optionHints: ["19", "45", "83"] },
  ],
  "G1_W22_MATH": [
    { label: "So sánh dài hơn/ngắn hơn (2 vật)", feas: "image", skill: "Đo lường", promptHint: "Cây bút chì và cục tẩy, vật nào dài hơn?", optionHints: ["Cây bút chì", "Bằng nhau", "Cục tẩy"] },
    { label: "Tìm vật ngắn hơn 1 vật mốc", feas: "image", skill: "Đo lường", promptHint: "Con sâu B ngắn hơn con sâu A. Con sâu nào là con sâu B?", optionHints: ["Con sâu có 7 đốt", "Con sâu có 4 đốt"] },
    { label: "So sánh nhiều cặp vật liên tiếp", feas: "image", skill: "So sánh", promptHint: "So sánh 4 chìa khoá A, B, C, D. Chìa khoá nào dài nhất?", optionHints: ["Chìa khoá B", "Chìa khoá C", "Chìa khoá A", "Chìa khoá D"] },
    { label: "Tìm dài nhất/ngắn nhất trong 3 vật", feas: "image", skill: "Đo lường", promptHint: "3 con cá A, B, C có độ dài khác nhau. Con nào dài nhất?", optionHints: ["Con cá C", "Con cá A", "Con cá B"] },
    { label: "So sánh cao hơn/thấp hơn (con vật/người)", feas: "image", skill: "Đo lường", promptHint: "Con khỉ và con sư tử, con nào cao hơn?", optionHints: ["Bằng nhau", "Con khỉ", "Con sư tử"] },
    { label: "Tìm cao nhất/thấp nhất trong 1 hàng", feas: "image", skill: "Đo lường", promptHint: "5 cây trong vườn cao thấp khác nhau. Cây nào cao nhất?", optionHints: ["Cây D", "Cây A", "Cây C", "Cây B"] },
  ],
  "G1_W23_MATH": [
    { label: "So sánh dài hơn/ngắn hơn (2 vật)", feas: "image", skill: "Đo lường", promptHint: "Cây bút chì và cục tẩy, vật nào dài hơn?", optionHints: ["Cây bút chì", "Bằng nhau", "Cục tẩy"] },
    { label: "Tìm vật ngắn hơn 1 vật mốc", feas: "image", skill: "Đo lường", promptHint: "Con sâu B ngắn hơn con sâu A. Con sâu nào là con sâu B?", optionHints: ["Con sâu có 7 đốt", "Con sâu có 4 đốt"] },
    { label: "So sánh nhiều cặp vật liên tiếp", feas: "image", skill: "So sánh", promptHint: "So sánh 4 chìa khoá A, B, C, D. Chìa khoá nào dài nhất?", optionHints: ["Chìa khoá C", "Chìa khoá D", "Chìa khoá B", "Chìa khoá A"] },
    { label: "Tìm dài nhất/ngắn nhất trong 3 vật", feas: "image", skill: "Đo lường", promptHint: "3 con cá A, B, C có độ dài khác nhau. Con nào dài nhất?", optionHints: ["Con cá C", "Con cá B", "Con cá A"] },
    { label: "So sánh cao hơn/thấp hơn (con vật/người)", feas: "image", skill: "Đo lường", promptHint: "Con khỉ và con sư tử, con nào cao hơn?", optionHints: ["Bằng nhau", "Con khỉ", "Con sư tử"] },
    { label: "Tìm cao nhất/thấp nhất trong 1 hàng", feas: "image", skill: "Đo lường", promptHint: "5 cây trong vườn cao thấp khác nhau. Cây nào cao nhất?", optionHints: ["Cây B", "Cây D", "Cây A", "Cây C"] },
    { label: "Đo bằng đơn vị phi chuẩn (gang tay)", feas: "image", skill: "Đo lường", promptHint: "Bút chì dài 2 gang tay, thước dài 3 gang tay. Vật nào dài hơn?", optionHints: ["Bằng nhau", "Cái thước", "Cây bút chì"] },
    { label: "Nhận biết cách đặt thước đo ĐÚNG (bắt đầu từ vạch 0) [MỚI]", feas: "image", skill: "Đo lường", promptHint: "Bạn nào đặt thước đo bút chì ĐÚNG cách (bắt đầu từ vạch 0)?", optionHints: ["Bạn Mai", "Bạn Nam", "Bạn Việt"] },
    { label: "Đọc độ dài trên thước có vạch chia cm", feas: "image", skill: "Đo lường", promptHint: "Bút chì đo được 5cm trên thước. Bút chì dài bao nhiêu?", optionHints: ["6cm", "5cm", "4cm"] },
    { label: "Đếm ô vuông 1cm suy ra độ dài băng giấy", feas: "image", skill: "Đo lường", promptHint: "Băng giấy trải dài qua 7 ô vuông cạnh 1cm. Băng giấy dài bao nhiêu?", optionHints: ["6cm", "7cm", "8cm"] },
  ],
  "G1_W24_MATH": [
    { label: "Đo bằng đơn vị phi chuẩn (gang tay)", feas: "image", skill: "Đo lường", promptHint: "Bút chì dài 2 gang tay, thước dài 3 gang tay. Vật nào dài hơn?", optionHints: ["Cây bút chì", "Cái thước", "Bằng nhau"] },
    { label: "Nhận biết cách đặt thước đo ĐÚNG (bắt đầu từ vạch 0) [MỚI]", feas: "image", skill: "Đo lường", promptHint: "Bạn nào đặt thước đo bút chì ĐÚNG cách (bắt đầu từ vạch 0)?", optionHints: ["Bạn Mai", "Bạn Nam", "Bạn Việt"] },
    { label: "Đọc độ dài trên thước có vạch chia cm", feas: "image", skill: "Đo lường", promptHint: "Bút chì đo được 5cm trên thước. Bút chì dài bao nhiêu?", optionHints: ["5cm", "4cm", "6cm"] },
    { label: "Đếm ô vuông 1cm suy ra độ dài băng giấy", feas: "image", skill: "Đo lường", promptHint: "Băng giấy trải dài qua 7 ô vuông cạnh 1cm. Băng giấy dài bao nhiêu?", optionHints: ["7cm", "8cm", "6cm"] },
    { label: "Chọn số đo hợp lý trong thực tế (ước lượng)", feas: "formula", skill: "Đo lường", promptHint: "Bút mực trong thực tế dài khoảng bao nhiêu?", optionHints: ["khoảng 15cm", "khoảng 150cm", "khoảng 1,5cm"] },
    { label: "Đọc độ dài theo lưới ô vuông cho nhiều đồ vật", feas: "image", skill: "Đo lường", promptHint: "Xe tải đồ chơi trải dài qua 6 ô vuông cạnh 1cm. Xe dài bao nhiêu?", optionHints: ["7cm", "6cm", "5cm"] },
    { label: "Tìm vật dài hơn 1 ngưỡng cho trước", feas: "image", skill: "Đo lường", promptHint: "Trong 3 bút chì A(6cm) B(9cm) C(7cm), bút nào dài hơn 8cm?", optionHints: ["Bút A", "Bút B", "Bút C"] },
    { label: "So sánh dài hơn (đồ vật)", feas: "image", skill: "Đo lường", promptHint: "Bút chì và bút lông màu, vật nào dài hơn?", optionHints: ["Bút chì", "Bằng nhau", "Bút lông màu"] },
    { label: "Tìm cao nhất/thấp nhất trong nhóm bạn", feas: "image", skill: "Đo lường", promptHint: "4 bạn Nam, Mi, Việt, Mai cao thấp khác nhau. Bạn nào cao nhất?", optionHints: ["Bạn Việt", "Bạn Mai", "Bạn Mi", "Bạn Nam"] },
    { label: "So sánh 2 vật (vd ngựa/hươu cao cổ)", feas: "image", skill: "So sánh", promptHint: "Ngựa và hươu cao cổ, con nào cao hơn?", optionHints: ["Hươu cao cổ", "Ngựa", "Bằng nhau"] },
    { label: "Đo độ dài bằng cm", feas: "image", skill: "Đo lường", promptHint: "Cây bút sáp vàng đo được 8cm trên thước. Bút dài bao nhiêu?", optionHints: ["8cm", "9cm", "7cm"] },
    { label: "So sánh độ dài với 1 ngưỡng cho trước (vừa trong hộp)", feas: "image", skill: "Đo lường", promptHint: "Hộp bút dài 15cm. Vật nào cho VỪA vào hộp: bút chì 9cm hay thước 20cm?", optionHints: ["Bút chì 9cm", "Cả hai đều vừa", "Thước 20cm"] },
    { label: "Suy luận thứ hạng từ bục đứng cao/thấp", feas: "image", skill: "Suy luận", promptHint: "Thỏ đứng bục cao nhất, cáo bục giữa, sóc bục thấp nhất. Ai về đích thứ nhất?", optionHints: ["Cáo", "Thỏ", "Sóc"] },
    { label: "So sánh khoảng cách qua đếm số đơn vị cách đều [MỚI]", feas: "image", skill: "Đếm số", promptHint: "9 cây trồng cách đều nhau. Cáo đứng gần cây thứ 2, thỏ đứng gần cây thứ 8. Cáo đứng gần thỏ hay gần sóc (cây thứ 1) hơn?", optionHints: ["Gần sóc hơn", "Bằng nhau", "Gần thỏ hơn"] },
    { label: "So sánh tổng chiều dài 2 tuyến đường chia đoạn [MỚI]", feas: "formula", skill: "So sánh", promptHint: "Đường A chia 2 đoạn 4m và 3m (tổng 7m). Đường B dài 7m. Đường nào ngắn hơn?", optionHints: ["Đường A", "Đường B", "Bằng nhau"] },
  ],
  "G1_W25_MATH": [
    { label: "Tính (đặt tính sẵn cột dọc)", feas: "formula", skill: "Tính toán", promptHint: "Tính: 33 + 1 = ?", optionHints: ["36", "34", "29", "31"] },
    { label: "Đặt tính rồi tính (yêu cầu trình bày cột dọc)", feas: "engine", skill: "Tính toán", promptHint: "Đặt tính rồi tính: 42 + 4", optionHints: ["47", "46", "45"] },
    { label: "Nối phép tính với kết quả", feas: "image", skill: "Tính toán", promptHint: "Phép tính 40 + 9 nối với kết quả nào?", optionHints: ["49", "48", "98"] },
    { label: "Toán lời văn 1 bước (có sơ đồ ?+?=?)", feas: "formula", skill: "Toán đố", promptHint: "Mai gấp được 12 chiếc thuyền giấy, Mi gấp được 5 chiếc. Hỏi cả hai gấp được bao nhiêu chiếc?", optionHints: ["17", "18", "12", "21"] },
    { label: "Bài toán ràng buộc \"vừa đủ chỗ chứa\"", feas: "image", skill: "Toán đố", promptHint: "Lá sen chở được 17 chú ếch, đang có 14 chú. Cần thêm mấy chú ếch để VỪA ĐỦ 17?", optionHints: ["4", "3", "2"] },
    { label: "Ghép cặp số từ 2 nhóm để cộng ra kết quả nhóm 3 [MỚI]", feas: "image", skill: "Phép cộng", promptHint: "Số nào cộng với 40 để được 42?", optionHints: ["3", "1", "2"] },
  ],
  "G1_W26_MATH": [
    { label: "Tính (đặt tính sẵn)", feas: "formula", skill: "Tính toán", promptHint: "Tính: 36 + 16 = ?", optionHints: ["49", "52", "48", "57"] },
    { label: "Đặt tính rồi tính (cột dọc)", feas: "engine", skill: "Tính toán", promptHint: "Đặt tính rồi tính: 13 + 21", optionHints: ["33", "34", "35"] },
    { label: "Nối phép tính với bãi đỗ kết quả", feas: "image", skill: "Tính toán", promptHint: "Trực thăng ghi 39 + 40 đỗ vào bãi có số nào?", optionHints: ["79", "90", "78"] },
    { label: "Toán lời văn 1 bước", feas: "formula", skill: "Toán đố", promptHint: "Cây cà chua thứ nhất có 11 quả, cây thứ hai có 16 quả. Hỏi cả hai cây có bao nhiêu quả?", optionHints: ["28", "23", "26", "27"] },
    { label: "Tìm lớn nhất/bé nhất kết quả trong 3 phép", feas: "image", skill: "So sánh", promptHint: "3 quả xoài ghi 2+40, 80+3, 70+10. Quả nào có kết quả LỚN NHẤT?", optionHints: ["70 + 10", "2 + 40", "80 + 3"] },
    { label: "Tính nhẩm tròn chục", feas: "formula", skill: "Tính toán", promptHint: "Tính nhẩm: 40 + 30 = ?", optionHints: ["68", "65", "70", "72"] },
    { label: "Vòng phép tính khép kín 4 đỉnh [MỚI]", feas: "image", skill: "Tính toán", promptHint: "Vòng lá cây 4 đỉnh: 30 →(+12)→ ? →(+11)→ ?... Đỉnh thứ hai là số mấy?", optionHints: ["41", "43", "42"] },
    { label: "Nối phép tính với kết quả", feas: "image", skill: "Tính toán", promptHint: "Phép tính 47 − 2 nối với kết quả nào?", optionHints: ["45", "44", "49"] },
    { label: "Đếm lùi từng bước 1 đơn vị", feas: "formula", skill: "Đếm số", promptHint: "Đếm lùi từ 8 đi 2 bước, mỗi bước 1 đơn vị. Còn lại mấy?", optionHints: ["10", "11", "6", "3"] },
    { label: "Đúng/Sai — đánh giá kết quả cho sẵn", feas: "image", skill: "Tính toán", promptHint: "Nhận định \"49 − 3 = 46\" là đúng hay sai?", optionHints: ["Đúng", "Sai"] },
    { label: "Ghép cặp phép tính cùng kết quả", feas: "image", skill: "Tính toán", promptHint: "Phép tính nào có cùng kết quả với 98 − 3?", optionHints: ["76 − 6", "96 − 1", "65 − 4"] },
    { label: "Họ phép tính cộng-trừ liên hệ (fact family)", feas: "formula", skill: "Phép cộng", promptHint: "Biết 11 + 5 = 16. Vậy 16 − 5 = ?", optionHints: ["15", "14", "13", "11"] },
    { label: "Dây chuyền phép tính", feas: "formula", skill: "Tính toán", promptHint: "Số? 47 →(−5)→ ? →(+1)→ ?", optionHints: ["43", "42", "45", "39"] },
    { label: "Tìm kết quả lớn hơn 1 ngưỡng cho trước", feas: "image", skill: "So sánh", promptHint: "Diều nào ghi phép tính có kết quả LỚN HƠN 55: 59-2, 59-6, 58-3?", optionHints: ["59 − 6", "58 − 3", "59 − 2"] },
  ],
  "G1_W27_MATH": [
    { label: "Tính (đặt tính sẵn)", feas: "formula", skill: "Tính toán", promptHint: "Tính: 86 − 41 = ?", optionHints: ["45", "41", "49", "43"] },
    { label: "Đặt tính rồi tính (cột dọc)", feas: "engine", skill: "Tính toán", promptHint: "Đặt tính rồi tính: 68 − 15", optionHints: ["52", "53", "54"] },
    { label: "Tìm lớn nhất kết quả trong 3 phép", feas: "image", skill: "So sánh", promptHint: "3 quả dưa ghi 70-20, 54-14, 35-10. Quả nào có kết quả LỚN NHẤT?", optionHints: ["70 − 20", "35 − 10", "54 − 14"] },
    { label: "Toán lời văn 1 bước", feas: "formula", skill: "Toán đố", promptHint: "Vườn cây có 66 cây nhãn và vải, trong đó có 39 cây nhãn. Hỏi có bao nhiêu cây vải?", optionHints: ["27", "30", "29", "32"] },
    { label: "Tính nhẩm tròn chục", feas: "formula", skill: "Tính toán", promptHint: "Tính nhẩm: 50 − 20 = ?", optionHints: ["30", "26", "29", "31"] },
    { label: "Dây chuyền phép tính", feas: "formula", skill: "Tính toán", promptHint: "Số? 69 →(−10)→ ? →(−20)→ ?", optionHints: ["39", "36", "40", "35"] },
    { label: "Họ phép tính (fact family)", feas: "formula", skill: "Tính toán", promptHint: "Biết 61 + 26 = 87. Vậy 87 − 61 = ?", optionHints: ["27", "26", "22", "29"] },
    { label: "Tìm lớn nhất trong 4 đáp án cho sẵn", feas: "image", skill: "So sánh", promptHint: "4 bạn cầm thẻ ghi phép tính: 65-41, 89-60, 58-30, 67-36. Bạn nào có kết quả LỚN NHẤT?", optionHints: ["65 − 41", "67 − 36", "89 − 60", "58 − 30"] },
    { label: "So sánh chiều cao (liên hệ đo độ dài)", feas: "image", skill: "Đo lường", promptHint: "3 rô-bốt cao 87cm, 97cm, 91cm. Rô-bốt nào cao nhất?", optionHints: ["Rô-bốt 97cm", "Rô-bốt 91cm", "Rô-bốt 87cm"] },
  ],
  "G1_W28_MATH": [
    { label: "Tính / tính nhẩm tổng hợp", feas: "formula", skill: "Tính toán", promptHint: "Tính: 69 − 7 = ?", optionHints: ["59", "62", "58", "60"] },
    { label: "Cộng dồn khoảng cách theo sơ đồ đường bay/đường đi", feas: "image", skill: "Phép cộng", promptHint: "Cầu bay qua 3 điểm cách nhau 10, 5, 4 bước chân. Tổng quãng đường bay là bao nhiêu bước chân?", optionHints: ["18", "20", "19"] },
    { label: "Sửa lỗi phép tính bằng hoán đổi 2 phần tử [MỚI]", feas: "image", skill: "Tính toán", promptHint: "Phép tính xếp nhầm: 98 − 73 = 52 (sai, do đổi nhầm 2 đốt tre). Phép tính nào ĐÚNG sau khi đổi lại?", optionHints: ["73 − 98 = 52", "93 − 78 = 15", "98 − 73 = 52"] },
    { label: "Đặt tính rồi tính (cột dọc)", feas: "engine", skill: "Tính toán", promptHint: "Đặt tính rồi tính: 23 + 5", optionHints: ["28", "29", "27"] },
    { label: "Dây chuyền 2 chiều — thứ tự phép tính đảo ngược", feas: "formula", skill: "Tính toán", promptHint: "Số? 20 →(+12)→ ? →(−5)→ ?", optionHints: ["28", "27", "31", "25"] },
    { label: "Mảnh ghép jigsaw 2 nửa chứa phép tính ẩn [MỚI]", feas: "image", skill: "Tính toán", promptHint: "Mảnh ghép lục giác: nửa trái ghi 2, nửa phải ghi ?, biết 2 + ? = 6. Nửa phải ghi số mấy?", optionHints: ["3", "5", "4"] },
    { label: "Toán lời văn nhiều bước", feas: "formula", skill: "Toán đố", promptHint: "Có 69 quả. Hái đi 17 quả, rồi rụng thêm 4 quả. Hỏi còn lại bao nhiêu quả?", optionHints: ["48", "44", "46", "45"] },
    { label: "Tháp số cộng dồn", feas: "image", skill: "Phép cộng", promptHint: "Tháp gạch: đáy 10,11,12,10. Ô đầu tầng 2 là 10+11=21. Ô thứ hai tầng 2 là mấy?", optionHints: ["23", "24", "22"] },
    { label: "Bài toán cân bằng / đẳng thức (cân 2 bên bằng nhau) [MỚI]", feas: "formula", skill: "Toán đố", promptHint: "Cân thăng bằng: 1 bên có túi đỏ (?), bên kia có 2 túi 39 và 24. Túi đỏ nặng bao nhiêu?", optionHints: ["68", "63", "67", "58"] },
    { label: "Phép tính 3 số hạng (số 2 chữ số)", feas: "formula", skill: "Tính toán", promptHint: "Tính: 19 + 1 + 7 = ?", optionHints: ["27", "28", "31", "26"] },
  ],
  "G1_W29_MATH": [
    { label: "Tính / tính nhẩm tổng hợp", feas: "formula", skill: "Tính toán", promptHint: "Tính: 27 − 15 = ?", optionHints: ["16", "12", "7", "15"] },
    { label: "Cộng dồn khoảng cách theo sơ đồ đường bay/đường đi", feas: "image", skill: "Phép cộng", promptHint: "Cầu bay qua 3 điểm cách nhau 10, 5, 4 bước chân. Tổng quãng đường bay là bao nhiêu bước chân?", optionHints: ["20", "18", "19"] },
    { label: "Sửa lỗi phép tính bằng hoán đổi 2 phần tử [MỚI]", feas: "image", skill: "Tính toán", promptHint: "Phép tính xếp nhầm: 98 − 73 = 52 (sai, do đổi nhầm 2 đốt tre). Phép tính nào ĐÚNG sau khi đổi lại?", optionHints: ["93 − 78 = 15", "73 − 98 = 52", "98 − 73 = 52"] },
    { label: "Đặt tính rồi tính (cột dọc)", feas: "engine", skill: "Tính toán", promptHint: "Đặt tính rồi tính: 23 + 5", optionHints: ["29", "27", "28"] },
    { label: "Dây chuyền 2 chiều — thứ tự phép tính đảo ngược", feas: "formula", skill: "Tính toán", promptHint: "Số? 38 →(+6)→ ? →(−24)→ ?", optionHints: ["17", "25", "20", "18"] },
    { label: "Mảnh ghép jigsaw 2 nửa chứa phép tính ẩn [MỚI]", feas: "image", skill: "Tính toán", promptHint: "Mảnh ghép lục giác: nửa trái ghi 2, nửa phải ghi ?, biết 2 + ? = 6. Nửa phải ghi số mấy?", optionHints: ["5", "4", "3"] },
    { label: "Toán lời văn nhiều bước", feas: "formula", skill: "Toán đố", promptHint: "Có 71 quả. Hái đi 34 quả, rồi rụng thêm 6 quả. Hỏi còn lại bao nhiêu quả?", optionHints: ["31", "32", "29", "30"] },
    { label: "Tháp số cộng dồn", feas: "image", skill: "Phép cộng", promptHint: "Tháp gạch: đáy 10,11,12,10. Ô đầu tầng 2 là 10+11=21. Ô thứ hai tầng 2 là mấy?", optionHints: ["22", "24", "23"] },
    { label: "Bài toán cân bằng / đẳng thức (cân 2 bên bằng nhau) [MỚI]", feas: "formula", skill: "Toán đố", promptHint: "Cân thăng bằng: 1 bên có túi đỏ (?), bên kia có 2 túi 16 và 38. Túi đỏ nặng bao nhiêu?", optionHints: ["54", "58", "51", "53"] },
    { label: "Phép tính 3 số hạng (số 2 chữ số)", feas: "formula", skill: "Tính toán", promptHint: "Tính: 22 + 7 + 9 = ?", optionHints: ["36", "38", "33", "40"] },
  ],
  "G1_W30_MATH": [
    { label: "Xem giờ theo hoạt động trong ngày (sáng/trưa/chiều/tối)", feas: "image", skill: "Xem giờ", promptHint: "Buổi trưa, các bạn ăn cơm lúc mấy giờ (theo tranh)?", optionHints: ["5 giờ", "12 giờ", "7 giờ"] },
    { label: "Đọc giờ trên đồng hồ (nhiều mặt đồng hồ)", feas: "formula", skill: "Xem giờ", promptHint: "Kim giờ chỉ số 2, kim phút chỉ số 12. Là mấy giờ?", optionHints: ["7 giờ", "3 giờ", "2 giờ", "4 giờ"] },
    { label: "Đúng/Sai — nhận định về giờ trên đồng hồ", feas: "image", skill: "Xem giờ", promptHint: "Kim giờ và kim phút trùng nhau tại số 12. Rô-bốt nói \"Đồng hồ chỉ 12 giờ\" — đúng hay sai?", optionHints: ["Sai", "Đúng"] },
    { label: "Tìm bạn cầm đồng hồ theo giờ cho trước", feas: "image", skill: "Xem giờ", promptHint: "5 bạn cầm đồng hồ giờ khác nhau. Bạn nào cầm đồng hồ chỉ 7 giờ?", optionHints: ["Bạn Nam", "Bạn Mai", "Bạn Việt"] },
    { label: "Xem giờ đi ngủ của động vật", feas: "image", skill: "Xem giờ", promptHint: "Con cú đi ngủ lúc mấy giờ (theo tranh)?", optionHints: ["9 giờ tối", "6 giờ sáng", "6 giờ tối"] },
    { label: "Đọc giờ nhiều địa điểm rồi suy luận \"xem được gì\"", feas: "image", skill: "Xem giờ", promptHint: "Công viên có 5 tiết mục theo giờ. Nếu Mi đến lúc 2 giờ chiều, Mi xem được tiết mục nào bắt đầu SAU 2 giờ?", optionHints: ["Ảo thuật (1 giờ)", "Nhạc nước (12 giờ)", "Xiếc cá heo (3 giờ)"] },
    { label: "Đọc thứ trong tuần theo mốc cho trước (cây nảy mầm)", feas: "image", skill: "Xem lịch", promptHint: "Cây đậu thần gieo Thứ hai, nảy mầm sau 2 ngày. Nảy mầm vào thứ mấy?", optionHints: ["Thứ Tư", "Thứ Năm", "Thứ Ba"] },
    { label: "Điền thứ còn thiếu liên tiếp", feas: "formula", skill: "Xem lịch", promptHint: "Điền thứ còn thiếu: Thứ hai, ?, Thứ tư, ?", optionHints: ["Thứ tư, Thứ sáu", "Thứ ba, Thứ năm", "Thứ năm, Thứ bảy"] },
    { label: "Suy luận Hôm qua/Hôm nay/Ngày mai từ 1 mốc", feas: "formula", skill: "Xem lịch", promptHint: "Hôm nay là thứ Tư. Vậy ngày mai là thứ mấy?", optionHints: ["Thứ Ba", "Thứ Sáu", "Thứ Năm"] },
    { label: "Đọc thời khoá biểu 2 chiều (ngày × tiết)", feas: "image", skill: "Xem lịch", promptHint: "Xem thời khoá biểu: Rô-bốt học Tiếng Việt vào những ngày nào?", optionHints: ["Chỉ thứ ba", "Cả tuần", "Thứ hai và thứ tư"] },
    { label: "Suy luận ánh xạ thứ tự ↔ thứ trong tuần (bản đồ du lịch)", feas: "image", skill: "Xem lịch", promptHint: "Thứ hai Rô-bốt ở Cao Bằng (điểm 1). Mỗi ngày 1 điểm khác. Thứ ba Rô-bốt ở đâu (điểm 2)?", optionHints: ["Đà Nẵng", "Ninh Bình", "Hà Nội"] },
  ],
  "G1_W31_MATH": [
    { label: "Suy luận ngày từ thứ trong tuần (nối)", feas: "image", skill: "Xem lịch", promptHint: "Biết thứ ba là ngày 22. Thứ năm là ngày mấy?", optionHints: ["25", "23", "24"] },
    { label: "Suy luận Hôm qua/Nay/Mai ↔ ngày cụ thể", feas: "image", skill: "Xem lịch", promptHint: "Hôm nay ngày 21. Ngày mai là ngày mấy?", optionHints: ["23", "22", "20"] },
    { label: "Suy luận số tờ lịch đã xé giữa 2 mốc", feas: "formula", skill: "Xem lịch", promptHint: "Tờ lịch cũ ghi ngày 12, tờ lịch mới ghi ngày 17. Đã xé mấy tờ lịch?", optionHints: ["3", "8", "10", "5"] },
    { label: "Xem giờ nhiều hoạt động (truyện Rùa và Thỏ)", feas: "image", skill: "Xem giờ", promptHint: "Rùa và Thỏ xuất phát lúc mấy giờ (theo tranh)?", optionHints: ["8 giờ", "9 giờ", "10 giờ"] },
    { label: "Đọc giờ đối chiếu bảng giờ chuyến bay", feas: "image", skill: "Xem giờ", promptHint: "Bảng giờ bay: Hà Nội - Đà Nẵng lúc 7 giờ. Em lên máy bay màu nào để đi Đà Nẵng?", optionHints: ["Máy bay đỏ", "Máy bay vàng", "Máy bay xanh"] },
    { label: "Tính khoảng thời gian trôi qua giữa 2 mốc giờ [MỚI]", feas: "formula", skill: "Xem giờ", promptHint: "Gia đình xuất phát lúc 8 giờ, về đến nhà lúc 11 giờ. Hỏi đi hết mấy giờ?", optionHints: ["3 giờ", "1 giờ", "6 giờ", "2 giờ"] },
  ],
  "G1_W32_MATH": [
    { label: "Đọc giờ trên đồng hồ", feas: "formula", skill: "Xem giờ", promptHint: "Kim giờ chỉ số 5, kim phút chỉ số 12. Là mấy giờ?", optionHints: ["10 giờ", "9 giờ", "5 giờ", "0 giờ"] },
    { label: "Đọc bảng lịch tuần 2 chiều (môn thể thao)", feas: "image", skill: "Xem lịch", promptHint: "Lịch chơi thể thao tuần: Rô-bốt chơi môn gì vào thứ tư?", optionHints: ["Bơi lội", "Cầu lông", "Bóng đá"] },
    { label: "Liệt kê theo điều kiện trên bảng số liệu (ăn bằng nhau/nhiều hơn)", feas: "image", skill: "Dãy số", promptHint: "Bảng số củ cà rốt 7 ngày. Thứ mấy đàn thỏ ăn NHIỀU HƠN 27 củ?", optionHints: ["Thứ ba (20 củ)", "Thứ năm (31 củ)", "Thứ tư (28 củ)"] },
    { label: "Suy luận chuỗi ngày từ đoạn hội thoại [MỚI]", feas: "formula", skill: "Xem lịch", promptHint: "Ba bạn nói chuyện: \"Hôm qua là thứ Tư.\" Vậy hôm nay là thứ mấy?", optionHints: ["Thứ Sáu", "Thứ Năm", "Thứ Tư"] },
  ],
  "G1_W33_MATH": [
    { label: "Dãy số tăng/giảm — điền số thiếu", feas: "formula", skill: "Dãy số", promptHint: "Điền số còn thiếu: 5, 4, 3, ?", optionHints: ["1", "2", "6", "5"] },
    { label: "Lọc số theo điều kiện > ngưỡng", feas: "image", skill: "Tính toán", promptHint: "Trong các bông hoa ghi số 4,8,7,6,3 — bông nào ghi số LỚN HƠN 5?", optionHints: ["8", "3", "4"] },
    { label: "Suy luận sau khi chuyển 1 phần tử giữa 2 nhóm [MỚI]", feas: "image", skill: "Suy luận", promptHint: "Hàng trên có 8 xe, hàng dưới có 6 xe. Chuyển 1 xe từ trên xuống dưới. Câu nào đúng?", optionHints: ["Số xe hai hàng bằng nhau", "Hàng trên vẫn nhiều hơn", "Hàng dưới nhiều hơn"] },
    { label: "Điền số thứ tự giai đoạn phát triển (hoa sen)", feas: "formula", skill: "Dãy số", promptHint: "Các giai đoạn hoa sen: 1, 2, 3, ?, 5. Giai đoạn còn thiếu là số mấy?", optionHints: ["4", "0", "2", "1"] },
    { label: "Suy luận logic từ tập số + ràng buộc so sánh (không cần ảnh)", feas: "formula", skill: "So sánh", promptHint: "Điểm của Mai, Việt, Nam là 9, 10, 10 (không theo thứ tự). Biết điểm Mai cao hơn điểm Nam. Việt được mấy điểm?", optionHints: ["9", "10"] },
    { label: "Lọc phép tính có kết quả bằng X", feas: "image", skill: "Tính toán", promptHint: "Toa tàu nào ghi phép tính có kết quả bằng 8?", optionHints: ["8 − 1", "0 + 4", "9 − 1"] },
    { label: "Tìm điểm trùng kết quả giữa 2 tập hợp (chuồng/thỏ) [MỚI]", feas: "image", skill: "Tính toán", promptHint: "4 chuồng 4,7,9,10 và 4 thỏ ghi 10-3,6+3,8-4,5+2. Chuồng nào có 2 chú thỏ?", optionHints: ["Chuồng 7", "Chuồng 9", "Chuồng 4"] },
    { label: "So sánh biểu thức", feas: "formula", skill: "So sánh", promptHint: "Điền dấu thích hợp: 3+2 ... 10", optionHints: [">", "<", "="] },
    { label: "Đếm tần suất kết quả trùng khớp — thống kê đơn giản [MỚI]", feas: "image", skill: "Đếm số", promptHint: "5 bướm ghi phép tính, 5 hoa ghi số 2,4,5,7,8. Hoa số 7 có mấy bướm đậu vào?", optionHints: ["0", "1", "2"] },
    { label: "Đếm số que tính kiểu bảy đoạn (chữ số) [MỚI]", feas: "engine", skill: "Đếm số", promptHint: "Xếp số 8 bằng que tính (kiểu 7 đoạn) cần mấy que?", optionHints: ["6", "7", "5"] },
    { label: "Đếm số cách chọn cặp số cộng ra tổng cho trước (tổ hợp)", feas: "image", skill: "Đếm số", promptHint: "Từ các số 2,7,6,3,8, có mấy cặp cộng ra 10?", optionHints: ["2 cặp (2+8, 7+3)", "3 cặp", "1 cặp"] },
    { label: "Suy luận cấu tạo số từ 2 gợi ý cho trước", feas: "image", skill: "Tách số", promptHint: "Bé tuyết cầm 2 bóng bay ghi 30 và ?. Biết số tạo thành là 37. Bóng còn lại ghi số mấy?", optionHints: ["7", "8", "3"] },
    { label: "\"X = A0 + ?\" tách chục-đơn vị", feas: "engine", skill: "Tách số", promptHint: "53 = 50 + ?", optionHints: ["5", "8", "3"] },
    { label: "So sánh 3 số đo độ dài (bước chân) — tìm dài/ngắn nhất", feas: "formula", skill: "Đo lường", promptHint: "Bước chân của Mai, Việt, Nam là 28cm, 26cm, 30cm. Ai có bước chân DÀI NHẤT?", optionHints: ["Mai", "Việt", "Nam"] },
    { label: "Lập số 2 chữ số từ 3 thẻ số cho trước", feas: "formula", skill: "Tách số", promptHint: "Từ 2 trong 3 thẻ số 3, 0, 7, số nào GHÉP ĐƯỢC?", optionHints: ["70", "zero", "08"] },
    { label: "Tính nhẩm tròn chục", feas: "formula", skill: "Tính toán", promptHint: "Tính nhẩm: 30 + 20 = ?", optionHints: ["45", "55", "47", "50"] },
    { label: "Đặt tính rồi tính (cột dọc)", feas: "engine", skill: "Tính toán", promptHint: "Đặt tính rồi tính: 32 + 15", optionHints: ["46", "47", "48"] },
    { label: "Nối 2 phép tính cùng kết quả", feas: "image", skill: "Tính toán", promptHint: "Phép tính 35 + 12 có cùng kết quả với phép tính nào?", optionHints: ["40 + 7", "20 + 30", "30 + 17"] },
    { label: "Dây chuyền phép tính 3 bước", feas: "formula", skill: "Tính toán", promptHint: "Số? 42 →(+25)→ ? →(−21)→ ? →(+29)→ ?", optionHints: ["74", "75", "80", "73"] },
    { label: "Lọc kết quả theo ngưỡng cho trước", feas: "image", skill: "Tính toán", promptHint: "Ngôi sao nào ghi phép tính có kết quả LỚN HƠN 26: 67-41, 76-50, 23+3?", optionHints: ["76 − 50", "67 − 41", "23 + 3"] },
    { label: "Toán lời văn cộng/trừ phạm vi 100", feas: "formula", skill: "Phép cộng", promptHint: "Lớp em chăm sóc 89 cây hoa hồng. Sáng nay đã có 46 cây nở hoa. Hỏi còn bao nhiêu cây chưa nở?", optionHints: ["39", "43", "46", "44"] },
  ],
  "G1_W34_MATH": [
    { label: "Chọn khối đúng loại", feas: "image", skill: "Nhận diện", promptHint: "Trong 4 khối A-D, khối nào LÀ khối lập phương?", optionHints: ["Khối D", "Khối B", "Khối C", "Khối A"] },
    { label: "Đếm số hình theo loại trong hình ghép (robot)", feas: "image", skill: "Đếm số", promptHint: "Rô-bốt ghép từ hình vuông, tròn, tam giác. Có mấy hình vuông?", optionHints: ["6", "4", "5"] },
    { label: "Đếm số hình tam giác trong hình que tính", feas: "image", skill: "Đếm số", promptHint: "Hình ghép từ 9 que tính. Hình có mấy hình tam giác?", optionHints: ["6", "4", "5", "3"] },
    { label: "Quy luật lặp hình/khối theo chu kỳ", feas: "image", skill: "Quy luật", promptHint: "Dãy hình lặp chu kỳ 4: thoi, tam giác, tròn, chữ nhật, thoi, tam giác, tròn, ?. Hình còn thiếu là hình gì?", optionHints: ["Tròn", "Thoi", "Chữ nhật", "Tam giác"] },
    { label: "Chọn đồng hồ theo hoạt động trong ngày", feas: "image", skill: "Xem giờ", promptHint: "Hoạt động \"tập thể dục\" diễn ra lúc 6 giờ sáng. Chọn đồng hồ đúng.", optionHints: ["Đồng hồ chỉ 7 giờ", "Đồng hồ chỉ 6 giờ", "Đồng hồ chỉ 12 giờ"] },
    { label: "Suy luận thứ trong tuần từ 1 mốc ngày (MCQ 3 đáp án)", feas: "formula", skill: "Xem lịch", promptHint: "Trong 1 tuần, nếu ngày 20 là thứ Hai thì ngày 22 là thứ mấy?", optionHints: ["Thứ Sáu", "Thứ Năm", "Thứ Tư"] },
    { label: "Đo độ dài bằng cm", feas: "image", skill: "Đo lường", promptHint: "Dập ghim đo được 4cm trên thước. Dập ghim dài bao nhiêu?", optionHints: ["3cm", "4cm", "5cm"] },
    { label: "Tìm dài nhất/ngắn nhất trong 4 băng giấy", feas: "image", skill: "Đo lường", promptHint: "4 băng giấy A,B,C,D độ dài khác nhau (đếm ô vuông). Băng nào dài nhất?", optionHints: ["Băng A", "Băng B", "Băng C", "Băng D"] },
    { label: "Ước lượng đơn vị đo hợp lý (MCQ 3 đáp án)", feas: "formula", skill: "Đo lường", promptHint: "Gang tay của em dài khoảng bao nhiêu?", optionHints: ["khoảng 1cm", "khoảng 10cm", "khoảng 5cm"] },
  ],
  "G1_W35_MATH": [
    { label: "Sắp xếp thứ tự dãy số cho trước", feas: "formula", skill: "Dãy số", promptHint: "Số nào bé nhất trong 4 số: 52, 57, 39, 49?", optionHints: ["42", "40", "39", "43"] },
    { label: "Đặt tính rồi tính (cột dọc)", feas: "engine", skill: "Tính toán", promptHint: "Đặt tính rồi tính: 13 + 5", optionHints: ["18", "17", "19"] },
    { label: "Toán lời văn cộng/trừ", feas: "formula", skill: "Phép cộng", promptHint: "Mai hái được 38 bông hoa, Mi hái được 12 bông hoa. Hỏi cả hai chị em hái được bao nhiêu bông hoa?", optionHints: ["50", "51", "52", "49"] },
    { label: "Suy luận thứ trong tuần (MCQ 3 đáp án)", feas: "formula", skill: "Xem lịch", promptHint: "Nếu thứ ba là ngày 11 thì thứ sáu tuần đó là ngày mấy?", optionHints: ["Ngày 15", "Ngày 14", "Ngày 13"] },
    { label: "Đo độ dài — đọc thước (MCQ 3 đáp án)", feas: "image", skill: "Đo lường", promptHint: "Bút bi đo được 15cm trên thước. Bút bi dài bao nhiêu?", optionHints: ["14cm", "16cm", "15cm"] },
    { label: "Đếm hình lồng ghép (hình vuông lớn chứa 4 ô nhỏ)", feas: "image", skill: "Đếm số", promptHint: "Hình vuông lớn chia thành 4 ô vuông nhỏ. Hình có tất cả mấy hình vuông (kể cả hình lớn)?", optionHints: ["6", "5", "4"] },
  ],
};

export function getMathArchetypes(lessonCode: string): MathArchetype[] {
  return MATH_ARCHETYPES_G1[lessonCode] ?? [];
}
